curso: 
	xsltproc -o index.html curso.xsl curso.xml

cursoPetra:
	xsltproc --stringparam url "http://petra.euitio.uniovi.es/~labra/cursos/ext03/" -o index.html curso.xsl curso.xml

local:
	xsltproc --stringparam url "files/" -o index.html curso.xsl curso.xml